name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-node@v4.4.0
      with:
        node-version: '22'
    - run: npm install
    - run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2

    - uses: actions/setup-node@v4.4.0
      with:
        node-version: '22'
    - run: npm install
    - run: npm run build
      env:
        NODE_ENV: production

    - uses: actions/upload-artifact@v4.6.2
      with:
        name: webapp-artifact
        path: dist/

  create-release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4.2.1
      with:
        name: webapp-artifact
      
    - name: Create Release
      uses: softprops/action-gh-release@v2.2.2
      with:
        name: "Release baseada na branch main"
        tag_name: "v${{ github.run_number }}"
        target_commitish: main
        files: dist/**
      # env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: create-release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      pages: write
    steps:
    - uses: actions/download-artifact@v4.2.1
      with:
        name: webapp-artifact

    - uses: actions/deploy-pages@v4.0.5
      with:
        artifact_name: webapp-artifact