name: Docker Image CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Setup Buildx with Registry Cache
      uses: docker/setup-buildx-action@v3.10.0
      # with:
      #   driver-opts: |
      #     image=moby/buildkit:master
      #   # buildkitd-flags: --allow-insecure-entitlement security.insecure
      #   # Configura cache do registry
      #   config-inline: |
      #     {
      #       "registry": {
      #         "${{ secrets.REGISTRY_LOGIN_SERVER }}": {
      #           "mirrors": [],
      #           "http": true,
      #           "auth": {
      #             "username": "${{ secrets.REGISTRY_USERNAME }}",
      #             "password": "${{ secrets.REGISTRY_PASSWORD }}"
      #           }
      #         }
      #       }
      #     }

      # 4. Build e Push com cache
    - name: Build and Push
      run: |
        docker buildx build \
          --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ github.event.repository.name }}:$(date +%s) \
          --cache-from type=registry,ref=${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ github.event.repository.name }}:buildcache \
          --cache-to type=registry,ref=${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ github.event.repository.name }}:buildcache,mode=max \
          --push \
          .
      
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - run: echo "🍏 This job's status is ${{ job.status }}."
